language: rust

matrix:
  include:
    - os: linux
      dist: trusty
      env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - os: linux
      dist: trusty
      env: TARGET=x86_64-unknown-linux-gnu
      rust: beta

    - os: linux
      dist: trusty
      env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

    - os: linux
      dist: precise
      env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

    - os: osx     
      env: TARGET=x86_64-apple-darwin
      rust: stable

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;
