language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;
